export const HomePageRoute = '/'
export const LoginPageRoute = '/login'
export const RegistrationPageRoute = '/registration'
export const CommentsPageRoute = '/comments'
export const LogoutPageRoute = '/logout'
